name: release-autopull
on:
  push:
    branches: dev

jobs:
  distribute:
    name: distribute
    runs-on: ubuntu-latest
    steps:
    - name: git pull and restart pm2
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.REMOTE_IP}}
        username: ${{secrets.REMOTE_SSH_ID}}
        key: ${{secrets.REMOTE_PASSWORD}}
        port: ${{secrets.REMOTE_SSH_PORT}}
        script: |
            cd ${{secrets.REMOTE_DIR_NAME}}
            git pull https://github.com/gchoi96/seed.git dev
            pm2 restart seed

# https://minkukjo.github.io/devops/2020/08/29/Infra-23/