name: dev-autopull
on:
  push:
    branches: dev

jobs:
  distribute:
    name: distribute
    runs-on: ubuntu-latest
    steps:
    - name: git pull and restart pm2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
            cd ${{ secrets.REMOTE_DIR_NAME }}
            git pull origin dev
            yarn install
            yarn build
            pm2 restart seed