name: release-autopull
on:
  push:
    branches: release

jobs:
  distribute:
    name: distribute
    runs-on: ubuntu-latest
    steps:
    - name: git pull and restart docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.REMOTE_IP}}
        username: ${{secrets.REMOTE_SSH_ID}}
        password: ${{secrets.REMOTE_PASSWORD}}
        port: ${{secrets.REMOTE_SSH_PORT}}
        script: |
            cd ${{secrets.REMOTE_DIR_NAME}}
            git pull https://github.com/gchoi96/seed.git dev